# citadel/workflows/trivia.py
"""Daily trivia workflow: one shared multiple-choice question per day
(generated by the local Ollama model, same question for everyone in a
given BBS timezone day), answered with a single A-D reply. Answering
reveals yesterday's aggregate results.

Question generation reuses config.ai's connection settings (url/model/
timeout) but has its own structured-output prompt, separate from the
general chat system_prompt used by AskAICommand -- and falls back to a
small bundled question bank if the model produces anything that doesn't
parse cleanly, so the game never breaks even if generation flakes.
"""

import asyncio
import json
import logging
from datetime import date, datetime, timedelta, UTC
from zoneinfo import ZoneInfo

import requests

from citadel.transport.packets import ToUser
from citadel.workflows.base import Workflow, WorkflowState
from citadel.workflows.registry import register

log = logging.getLogger(__name__)

TRIVIA_SYSTEM_PROMPT = (
    'Generate one multiple-choice trivia question for a general audience. '
    'Respond with ONLY compact JSON, no markdown, no commentary, in exactly '
    'this shape: {"question": "...", "choices": ["...","...","...","..."], "correct_index": 0}. '
    'question must be under 150 characters. Each choice under 40 characters. '
    'correct_index is 0-3, indexing into choices.'
)

# Deterministic fallback bank, used whenever generation fails to parse.
# Selected by date so concurrent requests on a fallback day still agree.
FALLBACK_QUESTIONS = [
    ("What is the capital of France?", ["London", "Paris", "Berlin", "Madrid"], 1),
    ("How many legs does a spider have?", ["6", "8", "10", "12"], 1),
    ("What planet is known as the Red Planet?", ["Venus", "Jupiter", "Mars", "Saturn"], 2),
    ("What is the largest ocean on Earth?", ["Atlantic", "Indian", "Arctic", "Pacific"], 3),
    ("Who wrote 'Romeo and Juliet'?", ["Dickens", "Shakespeare", "Twain", "Austen"], 1),
    ("What is the chemical symbol for gold?", ["Ag", "Au", "Gd", "Go"], 1),
    ("How many continents are there?", ["5", "6", "7", "8"], 2),
    ("What gas do plants absorb from the air?", ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"], 2),
]


def _today_str(config) -> str:
    tz = ZoneInfo(config.bbs.get("timezone", "UTC"))
    return datetime.now(tz).date().isoformat()


def _fallback_question(question_date: str):
    idx = date.fromisoformat(question_date).toordinal() % len(FALLBACK_QUESTIONS)
    return FALLBACK_QUESTIONS[idx]


async def _generate_question(config):
    """Returns (question_text, choices, correct_index) from the local
    model, or None if generation/parsing failed for any reason."""
    ai_config = config.ai
    try:
        response = await asyncio.to_thread(
            requests.post,
            ai_config.get("ollama_url", "http://localhost:11434/api/generate"),
            json={
                "model": ai_config.get("model", "llama3.2:3b"),
                "prompt": TRIVIA_SYSTEM_PROMPT,
                "stream": False,
                "options": {"num_predict": 200},
            },
            timeout=ai_config.get("timeout", 60),
        )
        response.raise_for_status()
        text = response.json().get("response", "").strip()

        if text.startswith("```"):
            text = text.strip("`")
            if text.lower().startswith("json"):
                text = text[4:]
            text = text.strip()

        data = json.loads(text)
        question = data["question"]
        choices = data["choices"]
        correct_index = data["correct_index"]

        if not isinstance(question, str) or not question.strip():
            raise ValueError("empty question")
        if (not isinstance(choices, list) or len(choices) != 4
                or not all(isinstance(c, str) and c.strip() for c in choices)):
            raise ValueError("malformed choices")
        if not isinstance(correct_index, int) or not (0 <= correct_index <= 3):
            raise ValueError("correct_index out of range")

        return question.strip(), [c.strip() for c in choices], correct_index
    except Exception as err:
        log.warning(f"Trivia question generation failed, using fallback: {err}")
        return None


@register
class TriviaWorkflow(Workflow):
    kind = "trivia"

    async def start(self, context):
        state = context.session_mgr.get_session_state(context.session_id)
        username = state.username
        question_date = _today_str(context.config)

        question_text, choices, correct_index = await self._ensure_today_question(
            context, question_date)

        already = await context.db.execute(
            "SELECT 1 FROM trivia_responses WHERE username = ? AND question_date = ?",
            (username, question_date)
        )
        if already:
            context.session_mgr.clear_workflow(context.session_id)
            reveal = await self._yesterday_reveal(context, question_date)
            return ToUser(
                session_id=context.session_id,
                text=("You've already played today's trivia. Check back "
                      f"tomorrow to see how you did!\n\n{reveal}")
            )

        data = {
            "question_date": question_date,
            "choices": choices,
            "correct_index": correct_index,
        }
        context.session_mgr.set_workflow(
            context.session_id,
            WorkflowState(kind=self.kind, step=2, data=data)
        )
        choice_lines = "\n".join(
            f"{chr(65 + i)}) {c}" for i, c in enumerate(choices))
        return ToUser(
            session_id=context.session_id,
            text=f"{question_text}\n{choice_lines}\n\nReply with A, B, C, or D.",
            hints={"type": "text", "workflow": self.kind, "step": 2}
        )

    async def handle(self, context, command):
        step = context.wf_state.step
        data = context.wf_state.data

        if step == 2:
            answer_letter = (command or "").strip().upper()[:1]
            if answer_letter not in ("A", "B", "C", "D"):
                return ToUser(
                    session_id=context.session_id,
                    text="Please reply with A, B, C, or D.",
                    is_error=True,
                    error_code="invalid_trivia_answer",
                    hints={"type": "text", "workflow": self.kind, "step": 2}
                )

            answer_index = ord(answer_letter) - ord("A")
            correct_index = data["correct_index"]
            question_date = data["question_date"]
            # Graded and stored now, but deliberately not revealed until
            # tomorrow's reveal -- see _yesterday_reveal().
            correct = (answer_index == correct_index)

            state = context.session_mgr.get_session_state(context.session_id)
            username = state.username
            now = datetime.now(UTC).isoformat()

            await context.db.execute(
                "INSERT INTO trivia_responses "
                "(username, question_date, answer_index, correct, answered_at) "
                "VALUES (?, ?, ?, ?, ?)",
                (username, question_date, answer_index, correct, now)
            )
            context.session_mgr.clear_workflow(context.session_id)

            reveal = await self._yesterday_reveal(context, question_date)
            return ToUser(
                session_id=context.session_id,
                text=("Your answer is locked in! Check back tomorrow to "
                      f"see if you got it right.\n\n{reveal}")
            )

        return ToUser(
            session_id=context.session_id,
            text=f"Invalid trivia step: {step}",
            is_error=True,
            error_code="invalid_trivia_step"
        )

    async def cleanup(self, context):
        """Nothing to clean up -- no partial DB writes happen before the
        answer is submitted, unlike login/registration which bind a
        username to the session mid-flow."""
        pass

    #------------------------------------------------------------
    # helpers
    #------------------------------------------------------------

    async def _ensure_today_question(self, context, question_date):
        existing = await context.db.execute(
            "SELECT question_text, choices, correct_index FROM trivia_questions "
            "WHERE question_date = ?",
            (question_date,)
        )
        if not existing:
            generated = await _generate_question(context.config)
            if generated:
                question_text, choices, correct_index = generated
            else:
                question_text, choices, correct_index = _fallback_question(question_date)

            await context.db.execute(
                "INSERT OR IGNORE INTO trivia_questions "
                "(question_date, question_text, choices, correct_index) "
                "VALUES (?, ?, ?, ?)",
                (question_date, question_text, json.dumps(choices), correct_index)
            )
            # Re-select to get the canonical row in case another session
            # raced us and inserted first.
            existing = await context.db.execute(
                "SELECT question_text, choices, correct_index FROM trivia_questions "
                "WHERE question_date = ?",
                (question_date,)
            )

        question_text, choices_json, correct_index = existing[0]
        return question_text, json.loads(choices_json), correct_index

    async def _yesterday_reveal(self, context, today_str: str) -> str:
        yesterday_str = (date.fromisoformat(today_str) - timedelta(days=1)).isoformat()
        counts = await context.db.execute(
            "SELECT COUNT(*), SUM(correct) FROM trivia_responses WHERE question_date = ?",
            (yesterday_str,)
        )
        total, num_correct = counts[0]
        if not total:
            return f"Yesterday ({yesterday_str}): no one played."

        winners = await context.db.execute(
            "SELECT username FROM trivia_responses "
            "WHERE question_date = ? AND correct = 1 "
            "ORDER BY answered_at LIMIT 5",
            (yesterday_str,)
        )
        names = ", ".join(row[0] for row in winners)
        winners_line = f" \U0001F3C6 {names}" if names else ""
        return f"Yesterday ({yesterday_str}): {num_correct or 0}/{total} correct.{winners_line}"
